# Site settings
title: MF.W
email: wang_lichen@outlook.com
description: > #MF.W
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://cool.github.io" # the base hostname & protocol for your site
twitter_username: coolnameismy@hotmail.com
github_username:  coolnameismy

# Build settings
#markdown: kramdown
permalink: /:year/:month/:day/:title.html   #博文的固定链接
paginate: 10                                #分页时每页博文数量
author:                                     #自定义常亮
  name: MF.W
  email: wang_lichen@outlook.com
  link: http://cool.github.io
  weibo: http://weibo.com/mafeiwang
  github: http://github.com/mafeiwang
title: MF.W                             #自定义常量

# avatar头像及Favicon
avatar: https://avatars1.githubusercontent.com/u/5010799?v=3&amp;s=460
#favicon: http://7u2ho6.com1.z0.glb.clouddn.com/site-favicon.ico

locals:                                     #自定义常量
  tags: 标签
  about: 关于
active: 技术                                 #自定义常量
subscribe_rss: /pages/atom.xml              #订阅地址
markdown: kramdown                         #markdown解释器

# google analytics 设置
#ga:
#  id:
#  url:
#

# baidu analytics 设置

ba:
  src: //hm.baidu.com/hm.js?22d94317cfb9f9e0bb476228d9f79278

# disqus 设置
disqus:
  shortname: coolnameismy